name: R Package CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Install dependencies
      run: |
        install.packages("devtools")
        install.packages("testthat")
        install.packages("usethis")
        install.packages("roxygen2")
        install.packages("covr")

    - name: Run tests
      run: |
        devtools::test()

